/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VouchersRouteImport } from './routes/vouchers'
import { Route as TaxRouteImport } from './routes/tax'
import { Route as SieRouteImport } from './routes/sie'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FilingRouteImport } from './routes/filing'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as ClosingRouteImport } from './routes/closing'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'

const VouchersRoute = VouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxRoute = TaxRouteImport.update({
  id: '/tax',
  path: '/tax',
  getParentRoute: () => rootRouteImport,
} as any)
const SieRoute = SieRouteImport.update({
  id: '/sie',
  path: '/sie',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FilingRoute = FilingRouteImport.update({
  id: '/filing',
  path: '/filing',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ClosingRoute = ClosingRouteImport.update({
  id: '/closing',
  path: '/closing',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/assets': typeof AssetsRoute
  '/closing': typeof ClosingRoute
  '/compliance': typeof ComplianceRoute
  '/filing': typeof FilingRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/sie': typeof SieRoute
  '/tax': typeof TaxRoute
  '/vouchers': typeof VouchersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/assets': typeof AssetsRoute
  '/closing': typeof ClosingRoute
  '/compliance': typeof ComplianceRoute
  '/filing': typeof FilingRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/sie': typeof SieRoute
  '/tax': typeof TaxRoute
  '/vouchers': typeof VouchersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/assets': typeof AssetsRoute
  '/closing': typeof ClosingRoute
  '/compliance': typeof ComplianceRoute
  '/filing': typeof FilingRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/sie': typeof SieRoute
  '/tax': typeof TaxRoute
  '/vouchers': typeof VouchersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/assets'
    | '/closing'
    | '/compliance'
    | '/filing'
    | '/login'
    | '/reports'
    | '/sie'
    | '/tax'
    | '/vouchers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/assets'
    | '/closing'
    | '/compliance'
    | '/filing'
    | '/login'
    | '/reports'
    | '/sie'
    | '/tax'
    | '/vouchers'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/assets'
    | '/closing'
    | '/compliance'
    | '/filing'
    | '/login'
    | '/reports'
    | '/sie'
    | '/tax'
    | '/vouchers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  AssetsRoute: typeof AssetsRoute
  ClosingRoute: typeof ClosingRoute
  ComplianceRoute: typeof ComplianceRoute
  FilingRoute: typeof FilingRoute
  LoginRoute: typeof LoginRoute
  ReportsRoute: typeof ReportsRoute
  SieRoute: typeof SieRoute
  TaxRoute: typeof TaxRoute
  VouchersRoute: typeof VouchersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vouchers': {
      id: '/vouchers'
      path: '/vouchers'
      fullPath: '/vouchers'
      preLoaderRoute: typeof VouchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax': {
      id: '/tax'
      path: '/tax'
      fullPath: '/tax'
      preLoaderRoute: typeof TaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sie': {
      id: '/sie'
      path: '/sie'
      fullPath: '/sie'
      preLoaderRoute: typeof SieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filing': {
      id: '/filing'
      path: '/filing'
      fullPath: '/filing'
      preLoaderRoute: typeof FilingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/closing': {
      id: '/closing'
      path: '/closing'
      fullPath: '/closing'
      preLoaderRoute: typeof ClosingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  AssetsRoute: AssetsRoute,
  ClosingRoute: ClosingRoute,
  ComplianceRoute: ComplianceRoute,
  FilingRoute: FilingRoute,
  LoginRoute: LoginRoute,
  ReportsRoute: ReportsRoute,
  SieRoute: SieRoute,
  TaxRoute: TaxRoute,
  VouchersRoute: VouchersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
